<?php

return [
    'mdcat-reboot-60-day' => [
        'id' => 1,
        'slug' => 'mdcat-reboot-60-day',
        'title' => 'MDCAT Reboot: 60-Day Preparation Program',
        'price' => '₨ 2,000',
        'original_price' => null,
        'rating' => '4.9',
        'rating_count' => '10k',
        'lessons' => '10+ Lessons',
        'students' => '500+ Students',
        'success_badge' => '300+ Students Selected',
        'success_stories' => [
            [
                'name' => 'Fatima Noor',
                'college' => 'King Edward Medical University',
                'selection' => 'KEMU Lahore 2025',
                'score' => '178/200',
                'quote' => '60-Day Reboot Program ne mujhe consistent rakha. KEMU mein seat mil gayi — dream come true!',
                'course_label' => 'MDCAT Reboot',
                'profile_image' => 'frontend/img/success/student-fatima-noor.jpg',
                'proof_image' => null,
            ],
        ],
        'instructor' => 'DoctorsInn',
        'duration' => '60 Days',
        'level' => 'Beginner to Advanced',
        'language' => 'Urdu / English',
        'image' => 'frontend/img/course/course1-1.jpg',
        'detail_image' => 'frontend/img/course/course1-1.jpg',
        'instructor_image' => 'frontend/img/course/course-thumb1-1.png',
        'overview' => 'MDCAT Reboot is a structured 60-day preparation program designed to take you from basics to exam-ready. With daily study plans, topic-wise lessons, and regular mock tests — this program ensures consistent progress every single day.',
        'what_will_you_learn' => [
            'Complete Biology, Chemistry & Physics syllabus coverage',
            'Daily practice questions with detailed explanations',
            'Full-Length Mock Tests (MDCAT pattern)',
            'Time management strategies for exam day',
            'Weekly progress tracking and performance reports',
            'English & Logical Reasoning preparation',
        ],
        'curriculum' => [
            ['title' => 'Week 1-2', 'desc' => 'Biology — Cell Biology & Genetics'],
            ['title' => 'Week 3-4', 'desc' => 'Chemistry — Organic & Inorganic'],
            ['title' => 'Week 5-6', 'desc' => 'Physics — Mechanics & Electricity'],
            ['title' => 'Week 7-8', 'desc' => 'English + Logical Reasoning'],
            ['title' => 'Week 9-10', 'desc' => 'Revision + Full Mock Tests'],
            ['title' => 'Week 11-12', 'desc' => 'Past Papers + Final Exam Strategy'],
        ],
        'instructor_info' => [
            'name' => 'DoctorsInn',
            'image' => 'frontend/img/course/course-thumb1-1.png',
            'courses' => '8+ Courses',
            'students' => '1000+ Students',
            'bio' => "DoctorsInnElite is Pakistan's trusted MDCAT preparation platform with expert instructors, structured programs, and a proven track record of helping students crack medical entry tests.",
        ],
        'reviews' => [
            [
                'name' => 'Ali Hassan',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'Best 60-day plan I found online. My score improved by 35 marks!',
                'date' => '2 days ago',
            ],
            [
                'name' => 'Fatima Malik',
                'image' => 'frontend/img/success/student-fatima-noor.jpg',
                'rating' => 5,
                'comment' => 'Very organized course. Daily tasks kept me consistent throughout.',
                'date' => '1 week ago',
            ],
            [
                'name' => 'Usman Raza',
                'image' => 'frontend/img/success/student-usman-tariq.jpg',
                'rating' => 4,
                'comment' => 'Great content and affordable price. Highly recommended for MDCAT 2026.',
                'date' => '2 weeks ago',
            ],
        ],
    ],

    'mdcat-2026-parvaaz-flps' => [
        'id' => 2,
        'slug' => 'mdcat-2026-parvaaz-flps',
        'title' => 'MDCAT 2026 – PARVAAZ Full-Length Papers (FLPs)',
        'price' => '₨ 1,000',
        'original_price' => null,
        'rating' => '4.8',
        'rating_count' => '8.5k',
        'lessons' => '5+ Papers',
        'students' => '300+ Students',
        'success_badge' => '150+ Students Qualified',
        'success_stories' => [],
        'instructor' => 'DoctorsInn',
        'duration' => '60 Days',
        'level' => 'Intermediate',
        'language' => 'Urdu / English',
        'image' => 'frontend/img/course/course1-2.jpg',
        'detail_image' => 'frontend/img/course/course1-2.jpg',
        'instructor_image' => 'frontend/img/course/course-thumb1-1.png',
        'overview' => "PARVAAZ FLPs give you the real exam experience before the actual MDCAT. Attempt full-length papers strictly following PMC pattern, get detailed result analysis, and identify your weak areas before it's too late.",
        'what_will_you_learn' => [
            'PMC-pattern Full-Length Mock Papers',
            'Detailed score analysis after every test',
            'Subject-wise performance breakdown',
            'Rank comparison with other students',
            'Weak area identification & improvement tips',
            'Time pressure practice — just like real exam',
        ],
        'curriculum' => [
            ['title' => 'FLP 1', 'desc' => 'Biology + Chemistry Focus'],
            ['title' => 'FLP 2', 'desc' => 'Physics + English Focus'],
            ['title' => 'FLP 3', 'desc' => 'Mixed — Full Syllabus'],
            ['title' => 'FLP 4', 'desc' => 'Speed & Accuracy Test'],
            ['title' => 'FLP 5', 'desc' => 'Final Grand Mock (Complete MDCAT Pattern)'],
        ],
        'instructor_info' => [
            'name' => 'DoctorsInn',
            'image' => 'frontend/img/course/course-thumb1-1.png',
            'courses' => '8+ Courses',
            'students' => '1000+ Students',
            'bio' => "DoctorsInnElite is Pakistan's trusted MDCAT preparation platform with expert instructors, structured programs, and a proven track record of helping students crack medical entry tests.",
        ],
        'reviews' => [
            [
                'name' => 'Zainab Ahmed',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'FLPs were strictly according to PMC pattern. Boosted my exam confidence tremendously!',
                'date' => '3 days ago',
            ],
            [
                'name' => 'Bilal Tariq',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'The score analysis helped me fix my Physics weak spots.',
                'date' => '1 week ago',
            ],
            [
                'name' => 'Ayesha Noor',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 4,
                'comment' => 'Grand Mock was very close to actual MDCAT difficulty.',
                'date' => '2 weeks ago',
            ],
        ],
    ],

    'mdcat-2026-al-fateh-cts' => [
        'id' => 3,
        'slug' => 'mdcat-2026-al-fateh-cts',
        'title' => 'MDCAT 2026 – AL-FATEH Comprehensive Test Session (CTS)',
        'price' => '₨ 1,400',
        'original_price' => '₨ 2,000',
        'discount_tag' => '30% Off',
        'rating' => '4.9',
        'rating_count' => '9.2k',
        'lessons' => '35 Days',
        'students' => '400+ Students',
        'success_badge' => '200+ Selected in MDCAT 2025',
        'success_stories' => [
            [
                'name' => 'Ali Hassan',
                'college' => 'NUMS Rawalpindi',
                'selection' => 'NUMS 2025',
                'score' => '185/200',
                'quote' => 'AL-FATEH CTS ka har test real MDCAT jaisa tha. Main first attempt mein select ho gaya!',
                'course_label' => 'AL-FATEH CTS',
                'profile_image' => 'frontend/img/success/student-ali-hassan.jpg',
                'proof_image' => null,
            ],
        ],
        'instructor' => 'DoctorsInn',
        'duration' => '35 Days',
        'level' => 'Intermediate to Advanced',
        'language' => 'Urdu / English',
        'image' => 'frontend/img/course/course1-3.jpg',
        'detail_image' => 'frontend/img/course/course1-3.jpg',
        'instructor_image' => 'frontend/img/course/course-thumb1-1.png',
        'overview' => 'AL-FATEH CTS is a 35-day intensive test session covering the entire MDCAT syllabus through topic-wise tests, chapter tests, and full-length papers. Perfect for students in their final phase of preparation.',
        'what_will_you_learn' => [
            'Topic-wise & Chapter-wise Tests (All Subjects)',
            '35-day structured test schedule',
            'Instant result with answer keys',
            'Performance tracking over 35 days',
            'Expert feedback on common mistakes',
            'Final exam strategy sessions',
        ],
        'curriculum' => [
            ['title' => 'Phase 1 (Day 1-10)', 'desc' => 'Biology Chapter Tests'],
            ['title' => 'Phase 2 (Day 11-20)', 'desc' => 'Chemistry & Physics Tests'],
            ['title' => 'Phase 3 (Day 21-28)', 'desc' => 'English + Logical Reasoning'],
            ['title' => 'Phase 4 (Day 29-35)', 'desc' => 'Full Mock Tests + Revision'],
        ],
        'instructor_info' => [
            'name' => 'DoctorsInn',
            'image' => 'frontend/img/course/course-thumb1-1.png',
            'courses' => '8+ Courses',
            'students' => '1000+ Students',
            'bio' => "DoctorsInnElite is Pakistan's trusted MDCAT preparation platform with expert instructors, structured programs, and a proven track record of helping students crack medical entry tests.",
        ],
        'reviews' => [
            [
                'name' => 'Hamza Sheikh',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'The 35-day schedule made revision so smooth and stress-free.',
                'date' => '4 days ago',
            ],
            [
                'name' => 'Marium Khan',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'Worth every rupee! Answer keys with explanations are top notch.',
                'date' => '1 week ago',
            ],
            [
                'name' => 'Saad Farooq',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'Best test session in Pakistan for MDCAT aspirants.',
                'date' => '2 weeks ago',
            ],
        ],
    ],

    'amc-prep-course-2026-ansaar' => [
        'id' => 4,
        'slug' => 'amc-prep-course-2026-ansaar',
        'title' => 'AMC Prep Course 2026 – Ansaar Batch',
        'price' => '₨ 2,500',
        'original_price' => '₨ 3,000',
        'discount_tag' => '17% Off',
        'rating' => '4.8',
        'rating_count' => '6.4k',
        'lessons' => '12 Lessons',
        'students' => '200+ Students',
        'success_badge' => '50+ Selected in AMC 2025',
        'success_stories' => [
            [
                'name' => 'Usman Tariq',
                'college' => 'AMC Rawalpindi',
                'selection' => 'AMC Rawalpindi 2025',
                'score' => '190/200',
                'quote' => 'AMC Prep Course bilkul exam pattern par tha. Alhamdulillah AMC mein select!',
                'course_label' => 'AMC Ansaar Batch',
                'profile_image' => 'frontend/img/success/student-usman-tariq.jpg',
                'proof_image' => null,
            ],
        ],
        'instructor' => 'DoctorsInn',
        'duration' => 'Lifetime Access',
        'level' => 'Beginner to Advanced',
        'language' => 'Urdu / English',
        'image' => 'frontend/img/course/course1-4.jpg',
        'detail_image' => 'frontend/img/course/course1-4.jpg',
        'instructor_image' => 'frontend/img/course/course-thumb1-1.png',
        'overview' => 'The AMC Prep Course – Ansaar Batch is a comprehensive program designed for Armed Forces Medical College (AMC) aspirants. Get complete syllabus coverage, AMC-specific mock tests, and dedicated instructor support throughout your preparation.',
        'what_will_you_learn' => [
            'Complete AMC syllabus — Biology, Chemistry, Physics',
            'AMC-pattern Mock Tests & Past Papers',
            'English & Intelligence Test preparation',
            'Interview preparation tips',
            '12 structured video lessons',
            '1-on-1 mentor support via WhatsApp',
        ],
        'curriculum' => [
            ['title' => 'Lesson 1-3', 'desc' => 'Biology (Genetics, Physiology, Ecology)'],
            ['title' => 'Lesson 4-6', 'desc' => 'Chemistry (Organic, Physical, Analytical)'],
            ['title' => 'Lesson 7-9', 'desc' => 'Physics (Mechanics, Waves, Modern Physics)'],
            ['title' => 'Lesson 10', 'desc' => 'English + Intelligence Test'],
            ['title' => 'Lesson 11', 'desc' => 'AMC Past Papers Analysis'],
            ['title' => 'Lesson 12', 'desc' => 'Final Mock + Interview Tips'],
        ],
        'instructor_info' => [
            'name' => 'DoctorsInn',
            'image' => 'frontend/img/course/course-thumb1-1.png',
            'courses' => '8+ Courses',
            'students' => '1000+ Students',
            'bio' => "DoctorsInnElite is Pakistan's trusted MDCAT preparation platform with expert instructors, structured programs, and a proven track record of helping students crack medical entry tests.",
        ],
        'reviews' => [
            [
                'name' => 'Captain Aspirant',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'Intelligence tests guidance was invaluable for AMC test.',
                'date' => '5 days ago',
            ],
            [
                'name' => 'Hira Naveed',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => '1-on-1 WhatsApp mentorship cleared all my doubts.',
                'date' => '1 week ago',
            ],
            [
                'name' => 'Daniyal Shah',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 4,
                'comment' => 'Very focused on AMC specific syllabus and interview tips.',
                'date' => '3 weeks ago',
            ],
        ],
    ],

    'kts-mock-test-doctorsinnelite' => [
        'id' => 5,
        'slug' => 'kts-mock-test-doctorsinnelite',
        'title' => 'KTS Mock Test X DoctorsInnElite',
        'price' => 'FREE',
        'original_price' => null,
        'rating' => '4.7',
        'rating_count' => '12k',
        'lessons' => '1 Mock Test',
        'students' => '600+ Students',
        'success_badge' => '600+ Students Attempted',
        'success_stories' => [],
        'instructor' => 'DoctorsInn',
        'duration' => '10 Weeks',
        'level' => 'All Levels',
        'language' => 'English',
        'image' => 'frontend/img/course/course1-5.jpg',
        'detail_image' => 'frontend/img/course/course1-5.jpg',
        'instructor_image' => 'frontend/img/course/course-thumb1-1.png',
        'overview' => 'KTS Mock Test is a FREE full-length mock test powered by DoctorsInnElite in collaboration with Khairpur Medical College. Test your MDCAT preparation level, get instant results, and see where you stand among hundreds of students.',
        'what_will_you_learn' => [
            'Real MDCAT exam experience — FREE',
            'Full-length PMC pattern paper',
            'Instant result with detailed answer key',
            'Subject-wise score breakdown',
            'National rank comparison',
            'Identify weak areas before actual MDCAT',
        ],
        'curriculum' => [
            ['title' => 'Section 1', 'desc' => 'Biology (68 MCQs)'],
            ['title' => 'Section 2', 'desc' => 'Chemistry (54 MCQs)'],
            ['title' => 'Section 3', 'desc' => 'Physics (54 MCQs)'],
            ['title' => 'Section 4', 'desc' => 'English (18 MCQs)'],
            ['title' => 'Section 5', 'desc' => 'Logical Reasoning (6 MCQs)'],
        ],
        'instructor_info' => [
            'name' => 'DoctorsInn',
            'image' => 'frontend/img/course/course-thumb1-1.png',
            'courses' => '8+ Courses',
            'students' => '1000+ Students',
            'bio' => "DoctorsInnElite is Pakistan's trusted MDCAT preparation platform with expert instructors, structured programs, and a proven track record of helping students crack medical entry tests.",
        ],
        'reviews' => [
            [
                'name' => 'Shahmeer Baloch',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'Unbelievable that this full-length test is completely free!',
                'date' => '2 days ago',
            ],
            [
                'name' => 'Kalsoom Bibi',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 5,
                'comment' => 'Instant answer keys and ranking helped me gauge my national standing.',
                'date' => '1 week ago',
            ],
            [
                'name' => 'Adeel Qureshi',
                'image' => 'frontend/img/success/student-ali-hassan.jpg',
                'rating' => 4,
                'comment' => 'Great initiative by DoctorsInnElite and Khairpur Medical College.',
                'date' => '2 weeks ago',
            ],
        ],
    ],
];
